name: Release Builds
on: workflow_dispatch
jobs:
  build_linux_static:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Retrieve version
        run: |
          echo "::set-output name=VERSION::$(shards version)"
        id: version
      - name: Build
        run: make static
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pog-${{ steps.version.outputs.VERSION }}-linux-x86_64-static
          path: bin/pog
  build_linux_macos:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Retrieve version
        run: |
          echo "::set-output name=VERSION::$(shards version)"
        id: version
      - name: Build
        run: make build
      - name: Upload artifact (MacOS)
        if: startsWith(matrix.os, 'macOS')
        uses: actions/upload-artifact@v3
        with:
          name: pog-${{ steps.version.outputs.VERSION }}-darwin-universal
          path: bin/pog
      - name: Upload artifact (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v3
        with:
          name: pog-${{ steps.version.outputs.VERSION }}-linux-x86_64
          path: bin/pog
  release:
    runs-on: ubuntu-latest
    needs: [build_linux_static, build_linux_macos]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ./GH_ARTIFACTS
      - name: Make all binaries executable
        run: chmod +x GH_ARTIFACTS/**/*
      - name: Create zips
        run: cd GH_ARTIFACTS && find . -maxdepth 1 -mindepth 1 -type d -execdir zip -jr '{}.zip' '{}' \; && cd ..
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            GH_ARTIFACTS/*.zip
